### ISSUE TITLE
How is this secured?

### ISSUE THREAD

**Issue by tmtong** [roulljdh/encrypted_shared_preferences#11]
I was so happy to find out this package, but then....

I took a look at the source code. One can look up the index of the encryption key list. The key is then used for decryption. 

And all the key happens to be AAAAAAAAAAAAAAAAAAAAAA==

How is this secured?

**Comment by farukprogrammer** [comment]
This [PR](https://github.com/roulljdh/encrypted_shared_preferences/pull/7) from @viplmad is the root cause of this problem. It's the wrong implementation of [encrypt](https://pub.dev/packages/encrypt) library.

For the key, It should be `Key.fromSecureRandom` instead of `Key.fromLength`

And for the IV It should be `IV.fromSecureRandom` instead of `IV.fromLength`

**Comment by roulljdh** [comment]
Hello, Thank you for the feedback. I just published ^3.0.0. It now uses `fromSecureRandom` for the Key and IV.
